import { expect, test } from '@playwright/test';

test('session URL restores scene and synchronized gallery is saved',async({page,request})=>{
 test.setTimeout(90_000);await page.goto('/');
 const picker=page.getByLabel('Open structure file');await picker.setInputFiles('public/examples/1UBQ.cif');await expect(page.getByRole('heading',{name:'1UBQ.cif'})).toBeVisible();await picker.setInputFiles('public/examples/1UBI.cif');await expect(page.getByRole('heading',{name:'1UBI.cif'})).toBeVisible();
 await page.getByRole('button',{name:'Export',exact:true}).click();const dialog=page.locator('dialog');
 const sharing=page.waitForResponse(r=>r.url().endsWith('/api/sessions')&&r.request().method()==='POST');await dialog.getByRole('button',{name:'Create session link'}).click();expect((await sharing).ok()).toBe(true);const shared=await dialog.getByLabel('Shared session URL').inputValue();expect(shared).toContain('?session=');
 const restored=await page.context().newPage();await restored.goto(`/${new URL(shared).search}`);await expect(restored.getByRole('main')).toHaveAttribute('data-loaded','true',{timeout:30_000});await restored.getByRole('button',{name:'Manage structures'}).click();await expect(restored.locator('.scene-entry')).toHaveCount(2);await restored.close();
 const galleryResponse=page.waitForResponse(r=>r.url().endsWith('/api/exports')&&r.request().method()==='POST');await dialog.getByRole('button',{name:'Export synchronized gallery'}).click();const saved=await (await galleryResponse).json();expect((await request.get(saved.url)).ok()).toBe(true);await expect(dialog.getByAltText('Candidate gallery')).toBeVisible();
});

test('video controls expose rotation axes and flipbook mode',async({page})=>{await page.goto('/');await page.getByLabel('Open structure file').setInputFiles('public/examples/example.cif');await page.getByRole('button',{name:'Export',exact:true}).click();const dialog=page.locator('dialog');await expect(dialog.getByLabel('Rotation axis')).toHaveValue('y');await dialog.getByLabel('Mode').selectOption('flipbook');await expect(dialog.getByRole('button',{name:'Record and save'})).toBeDisabled();});

test('records and saves a 360 degree video',async({page,request})=>{test.setTimeout(60_000);await page.goto('/');await page.getByLabel('Open structure file').setInputFiles('public/examples/example.cif');await page.getByRole('button',{name:'Export',exact:true}).click();const dialog=page.locator('dialog');await dialog.getByRole('slider').fill('2');const saving=page.waitForResponse(r=>r.url().endsWith('/api/videos')&&r.request().method()==='POST');await dialog.getByRole('button',{name:'Record and save'}).click();const response=await saving;expect(response.ok()).toBe(true);const file=await response.json();const downloaded=await request.get(file.url);expect(downloaded.ok()).toBe(true);expect(downloaded.headers()['content-type']).toMatch(/^video\/(mp4|webm)/);});

test('records a structure flipbook and restores visibility',async({page})=>{test.setTimeout(60_000);await page.goto('/');const picker=page.getByLabel('Open structure file');await picker.setInputFiles('public/examples/1UBQ.cif');await page.getByRole('heading',{name:'1UBQ.cif'}).waitFor();await picker.setInputFiles('public/examples/1UBI.cif');await page.getByRole('heading',{name:'1UBI.cif'}).waitFor();await page.getByRole('button',{name:'Export',exact:true}).click();const dialog=page.locator('dialog');await dialog.getByLabel('Mode').selectOption('flipbook');await dialog.getByRole('slider').fill('2');const saving=page.waitForResponse(r=>r.url().endsWith('/api/videos')&&r.request().method()==='POST');await dialog.getByRole('button',{name:'Record and save'}).click();expect((await saving).ok()).toBe(true);await dialog.getByRole('button',{name:'Close export'}).click();await page.getByRole('button',{name:'Manage structures'}).click();await expect(page.getByRole('checkbox',{name:'1UBQ.cif'})).toBeChecked();await expect(page.getByRole('checkbox',{name:'1UBI.cif'})).toBeChecked();});
