import {test,expect} from '@playwright/test';
import {unlink} from 'node:fs/promises';
test('language switch translates dialogs and errors, preserves scene, and persists',async({page})=>{
 await page.goto('/');await page.getByRole('button',{name:'Open',exact:true}).click();await page.getByText('Ubiquitin · 1UBQ',{exact:true}).click();await expect(page.getByRole('main')).toHaveAttribute('data-loaded','true');
 await page.getByRole('button',{name:'Language / 语言'}).click();await expect(page.locator('html')).toHaveAttribute('lang','zh-CN');await expect(page.getByRole('button',{name:'重置视角'})).toBeVisible();await expect(page.getByRole('main')).toHaveAttribute('data-loaded','true');
 await page.getByRole('button',{name:'管理结构'}).click();await expect(page.getByRole('combobox',{name:'链配色'})).toBeVisible();await expect(page.getByRole('checkbox',{name:'水',exact:true})).not.toBeChecked();await expect(page.getByRole('button',{name:'自动调整可见结构的视角'})).toBeVisible();await page.setViewportSize({width:375,height:812});const panelBox=(await page.getByRole('complementary',{name:'结构',exact:true}).boundingBox())!;const openBox=(await page.getByRole('button',{name:'打开',exact:true}).boundingBox())!;expect(openBox.y+openBox.height).toBeLessThanOrEqual(panelBox.y);await page.screenshot({path:`test-results/chinese-narrow-${test.info().project.name}.png`});await page.setViewportSize({width:1194,height:834});await page.getByRole('button',{name:'关闭结构面板'}).click();
 await page.getByRole('button',{name:'叠合',exact:true}).click();await expect(page.getByRole('button',{name:'快速叠合两个文件'})).toBeDisabled();await expect(page.getByRole('combobox',{name:'对应关系'})).toBeVisible();await page.getByRole('button',{name:'关闭叠合面板'}).click();
 await page.getByRole('button',{name:'打开',exact:true}).click();await expect(page.getByRole('heading',{name:'按场景选择示例'})).toBeVisible();await expect(page.getByText('蛋白质同源二聚体',{exact:true})).toBeVisible();await page.getByPlaceholder('PDB 编号，如 4HHB').fill('BAD');await page.getByRole('button',{name:'获取',exact:true}).click();await expect(page.getByRole('alert')).toContainText('请输入 PDB 编号');await page.getByRole('button',{name:'关闭打开结构窗口'}).click();
 await page.getByRole('button',{name:'导出',exact:true}).click();await expect(page.getByRole('checkbox',{name:'透明背景'})).toBeChecked();await page.getByRole('button',{name:'关闭导出窗口'}).click();await page.screenshot({path:`test-results/chinese-ui-${test.info().project.name}.png`});
 await page.reload();await expect(page.locator('html')).toHaveAttribute('lang','zh-CN');await expect(page.getByRole('button',{name:'试用示例'})).toBeVisible();await page.getByRole('button',{name:'Language / 语言'}).click();await expect(page.getByRole('button',{name:'Try Example'})).toBeVisible();
});
test('beta view rotates and fits visible atoms, then restores camera without moving structures',async({page,request})=>{
 const files:string[]=[];
 async function camera(){await page.getByRole('button',{name:'Export',exact:true}).click();const saving=page.waitForResponse(r=>r.url().endsWith('/api/exports')&&r.request().method()==='POST');await page.getByRole('button',{name:'Save PNG to Mac'}).click();const saved=await (await saving).json();files.push(saved.name,saved.name.replace('.png','.json'));const metadata=await(await request.get(saved.metadataUrl)).json();await page.getByRole('button',{name:'Close export'}).click();return metadata;}
 try{
  await page.goto('/');await page.getByRole('button',{name:'Open',exact:true}).click();await page.getByText('Deoxyhemoglobin · 4HHB',{exact:true}).click();await page.getByRole('heading',{name:'4HHB.cif',exact:true}).waitFor();await page.waitForTimeout(600);const before=await camera();
  await page.getByRole('button',{name:'Manage structures'}).click();await expect(page.getByRole('button',{name:'Undo view',exact:true})).toBeDisabled();await page.getByRole('button',{name:'Automatically orient visible structures'}).click();await expect(page.getByRole('main')).toHaveAttribute('aria-busy','false');await page.waitForTimeout(500);await page.getByRole('button',{name:'Close structures panel'}).click();const after=await camera();expect(after.camera.position).not.toEqual(before.camera.position);expect(after.transforms).toEqual(before.transforms);
  await page.getByRole('button',{name:'Manage structures'}).click();await page.getByRole('button',{name:'Undo view',exact:true}).click();await page.waitForTimeout(400);await page.getByRole('button',{name:'Close structures panel'}).click();const restored=await camera();for(let i=0;i<3;i++){expect(restored.camera.position[i]).toBeCloseTo(before.camera.position[i],5);expect(restored.camera.up[i]).toBeCloseTo(before.camera.up[i],5);}
  await page.getByRole('button',{name:'Manage structures'}).click();await page.getByRole('checkbox',{name:'4HHB.cif',exact:true}).uncheck();await page.getByRole('button',{name:'Automatically orient visible structures'}).click();await expect(page.getByRole('alert')).toContainText('No visible atoms');
 }finally{for(const file of files)await unlink(`scene-exports/${file}`).catch(()=>{});}
});
