import { useEffect, useMemo, useState } from 'react';
import { localize, useI18n } from '../i18n';
import type { AnnotationKind, BiomolViewer, ColorMapping, MeasurementResult, SceneStructure, SelectionState, SequenceChain } from '../viewer/types';

interface Props { viewer: BiomolViewer; scene: SceneStructure[]; selection: SelectionState; busy: boolean; additive: boolean; colorMapping:ColorMapping; onColorMapping:(mapping:ColorMapping)=>void; onAdditive:(value:boolean)=>void; onClose:()=>void; onMutate:<T>(work:(viewer:BiomolViewer)=>Promise<T>)=>Promise<T|undefined>; onRefresh:()=>void; }
const mappingOptions:{id:ColorMapping;label:string}[]=[{id:'chain',label:'Chain'},{id:'element',label:'Element'},{id:'aa-type',label:'Amino-acid type'},{id:'secondary',label:'Secondary structure'},{id:'hydrophobicity',label:'Hydrophobicity'},{id:'charge',label:'Charge'},{id:'confidence',label:'Confidence / pLDDT'},{id:'custom',label:'Custom scalar'}];
const annotationOptions:{id:AnnotationKind;label:string}[]=[{id:'pocket',label:'Potential pocket'},{id:'epitope',label:'Epitope'},{id:'paratope',label:'Paratope'},{id:'active-site',label:'Active site'},{id:'custom',label:'Custom'}];
export function AnalysisPanel(p:Props){
 const {language}=useI18n();const [mapping,setMapping]=useState<ColorMapping>(p.colorMapping),[scalar,setScalar]=useState('A,1,0\nA,10,1');const [kind,setKind]=useState<AnnotationKind>('pocket'),[name,setName]=useState(''),[color,setColor]=useState('#ff4f81');const [error,setError]=useState(''),[result,setResult]=useState<MeasurementResult>();
 useEffect(()=>p.onColorMapping(mapping),[mapping,p.onColorMapping]);
 const [structureId,setStructureId]=useState(p.scene[0]?.id||''),structure=p.scene.find(s=>s.id===structureId)||p.scene[0];const [chainId,setChainId]=useState(structure?.alignmentChains[0]?.chainId||'');
 useEffect(()=>{if(!structureId&&p.scene[0])setStructureId(p.scene[0].id);},[p.scene,structureId]);useEffect(()=>{if(structure&&!structure.alignmentChains.some(c=>c.chainId===chainId))setChainId(structure.alignmentChains[0]?.chainId||'');},[structure,chainId]);
 let sequence:SequenceChain|undefined;try{if(structure&&chainId)sequence=p.viewer.getSequence(structure.id,chainId);}catch{sequence=undefined;}
 const chains=structure?.alignmentChains||[], annotations=p.scene.flatMap(s=>s.annotations.map(a=>({structure:s,annotation:a})));
 async function run(work:(viewer:BiomolViewer)=>Promise<unknown>){setError('');try{await p.onMutate(work);p.onRefresh();}catch(e){setError(e instanceof Error?e.message:String(e));}}
 function measure(type:'distance'|'angle'|'dihedral'|'rmsd'|'radius'){setError('');try{setResult(p.viewer.measureSelection(type));}catch(e){setError(e instanceof Error?e.message:String(e));}}
 const formatted=useMemo(()=>result?`${result.kind==='interface-area'?'Interface area':result.kind[0].toUpperCase()+result.kind.slice(1)}: ${result.value.toFixed(result.unit==='°'?1:2)} ${result.unit}`:'',[result]);
 return localize(<aside className="analysis-panel" aria-label="Structure analysis"><header><h2>Structure analysis</h2><button aria-label="Close structure analysis" onClick={p.onClose}>×</button></header>
  <section><h3>Property colors</h3><label>Color by<select value={mapping} disabled={p.busy} onChange={e=>setMapping(e.target.value as ColorMapping)}>{mappingOptions.map(option=><option value={option.id} key={option.id}>{option.label}</option>)}</select></label>{mapping==='custom'&&<label>Scalar values<textarea value={scalar} onChange={e=>setScalar(e.target.value)} rows={4}/><small className="muted">One per line: chain,residue[,atom],value. Missing values appear gray.</small></label>}<button disabled={p.busy||!p.scene.length} onClick={()=>void run(v=>v.setColorMapping(mapping,mapping==='custom'?scalar:undefined))}>Apply color mapping</button></section>
  <section><h3>Residue annotations</h3><label>Annotation type<select value={kind} onChange={e=>setKind(e.target.value as AnnotationKind)}>{annotationOptions.map(option=><option value={option.id} key={option.id}>{option.label}</option>)}</select></label><div className="annotation-fields"><input aria-label="Annotation name" placeholder="Name" value={name} onChange={e=>setName(e.target.value)}/><input aria-label="Annotation color" type="color" value={color} onChange={e=>setColor(e.target.value)}/></div><label className="check-row"><input type="checkbox" checked={p.additive} onChange={e=>p.onAdditive(e.target.checked)}/>Select multiple residues on canvas</label><div className="entry-actions"><button disabled={p.busy||!p.selection.residues.length} onClick={()=>void run(v=>v.addAnnotation(kind,name||annotationOptions.find(o=>o.id===kind)!.label,color))}>Annotate selection</button><button disabled={p.busy||!p.scene.length} onClick={()=>void run(v=>v.suggestLigandPocket(name||'Ligand-contact pocket',color))}>Suggest ligand contacts</button></div><small className="muted">Contact suggestion selects protein residues near a visible ligand; inspect before interpreting it as a pocket.</small>{annotations.map(({structure,annotation})=><div className="annotation-row" key={annotation.id}><i style={{background:annotation.color}}/><span><strong>{annotation.name}</strong><small>{structure.metadata.fileName} · {annotation.residues.length} residues</small></span><button aria-label={`Remove ${annotation.name}`} onClick={()=>void run(v=>v.removeAnnotation(structure.id,annotation.id))}>×</button></div>)}</section>
  <section><h3>Sequence ↔ structure</h3><label>Structure<select value={structure?.id||''} onChange={e=>setStructureId(e.target.value)}>{p.scene.map(s=><option value={s.id} key={s.id}>{s.metadata.fileName}</option>)}</select></label><label>Chain<select value={chainId} onChange={e=>setChainId(e.target.value)}>{chains.map(c=><option value={c.chainId} key={c.chainId}>{c.authChainId||c.chainId} · {c.count} residues</option>)}</select></label><div className="sequence-legend"><span className="helix">Helix</span><span className="sheet">Sheet</span><span>Coil</span><span className="confidence">Confidence</span></div><div className="sequence-track" aria-label="Linked sequence">{sequence?.residues.map(residue=><button key={`${residue.residueNumber}${residue.insertionCode||''}`} title={`${residue.residueName} ${residue.authResidueNumber??residue.residueNumber}${residue.confidence!==undefined?` · confidence ${residue.confidence.toFixed(0)}`:''}${residue.annotations.map(a=>` · ${a.name}`).join('')}`} className={`sequence-residue ${residue.secondary}`} style={{'--confidence':`${residue.confidence??50}%`,'--annotation':residue.annotations[0]?.color||'transparent'} as React.CSSProperties} onClick={e=>p.viewer.selectSequenceResidue(sequence.structureId,residue,e.shiftKey||p.additive)}><span>{residue.code}</span><small>{residue.authResidueNumber??residue.residueNumber}</small></button>)}</div></section>
  <section><h3>Measurements</h3><p className="muted">Select residues in order. Measurements use protein Cα or nucleic-acid C4′ anchors.</p><div className="measure-grid">{(['distance','angle','dihedral','rmsd','radius'] as const).map(type=><button key={type} disabled={!p.selection.residues.length} onClick={()=>measure(type)}>{type[0].toUpperCase()+type.slice(1)}</button>)}</div><label>Interface chain A<select value={chains[0]?.chainId||''} id="interface-a">{chains.map(c=><option value={c.chainId} key={c.chainId}>{c.authChainId||c.chainId}</option>)}</select></label><label>Interface chain B<select defaultValue={chains[1]?.chainId||chains[0]?.chainId||''} id="interface-b">{chains.map(c=><option value={c.chainId} key={c.chainId}>{c.authChainId||c.chainId}</option>)}</select></label><button disabled={!structure||chains.length<2} onClick={()=>{setError('');try{const a=(document.getElementById('interface-a') as HTMLSelectElement).value,b=(document.getElementById('interface-b') as HTMLSelectElement).value;setResult(p.viewer.measureInterface(structure!.id,a,b));}catch(e){setError(e instanceof Error?e.message:String(e));}}}>Calculate interface area</button>{result&&<output className="measurement-result"><strong>{formatted}</strong><span>{result.detail}</span></output>}</section>
  {error&&<p className="fit-warning" role="alert">{error}</p>}
 </aside>,language);
}
