import { useEffect, useMemo, useState } from 'react';
import { localize, useI18n } from '../i18n';
import type { AutoAnnotationMode, BiomolViewer, ColorMapping, MeasurementResult, SceneStructure, SelectionState, SequenceChain } from '../viewer/types';

interface Props { viewer:BiomolViewer;scene:SceneStructure[];selection:SelectionState;busy:boolean;additive:boolean;colorMapping:ColorMapping;onColorMapping:(mapping:ColorMapping)=>void;onAdditive:(value:boolean)=>void;onClose:()=>void;onMutate:<T>(work:(viewer:BiomolViewer)=>Promise<T>)=>Promise<T|undefined>;onRefresh:()=>void; }
const mappings:{id:ColorMapping;label:string}[]=[{id:'chain',label:'Chain'},{id:'element',label:'Element'},{id:'aa-type',label:'Amino-acid type'},{id:'secondary',label:'Secondary structure'},{id:'hydrophobicity',label:'Hydrophobicity'},{id:'charge',label:'Charge'},{id:'confidence',label:'Confidence / pLDDT'},{id:'custom',label:'Custom scalar'}];
const detectors:{id:AutoAnnotationMode;label:string;help:string}[]=[
 {id:'source-sites',label:'Deposited functional sites',help:'Reads explicit struct_site residues from PDBx/mmCIF.'},
 {id:'pocket-geometry',label:'Geometry pocket candidate · Beta',help:'Finds a bounded, surface-accessible concavity from coordinates alone.'},
 {id:'interface-pair',label:'Epitope / paratope interface',help:'Annotates both sides of a selected chain pair using 5 Å heavy-atom contacts.'},
];
export function AnalysisPanel(p:Props){
 const {language}=useI18n();const [mapping,setMapping]=useState<ColorMapping>(p.colorMapping),[scalar,setScalar]=useState('A,1,0\nA,10,1'),[detector,setDetector]=useState<AutoAnnotationMode>('source-sites'),[error,setError]=useState(''),[result,setResult]=useState<MeasurementResult>(),[zoom,setZoom]=useState(30),[rangeStart,setRangeStart]=useState(''),[rangeEnd,setRangeEnd]=useState('');
 const [structureId,setStructureId]=useState(p.scene[0]?.id||''),structure=p.scene.find(s=>s.id===structureId)||p.scene[0],[chainId,setChainId]=useState(structure?.alignmentChains[0]?.chainId||''),[chainB,setChainB]=useState(structure?.alignmentChains[1]?.chainId||'');
 useEffect(()=>p.onColorMapping(mapping),[mapping,p.onColorMapping]);useEffect(()=>{if(!structureId&&p.scene[0])setStructureId(p.scene[0].id);},[p.scene,structureId]);useEffect(()=>{if(structure&&!structure.alignmentChains.some(c=>c.chainId===chainId))setChainId(structure.alignmentChains[0]?.chainId||'');if(structure&&!structure.alignmentChains.some(c=>c.chainId===chainB))setChainB(structure.alignmentChains[1]?.chainId||'');},[structure,chainId,chainB]);
 let sequence:SequenceChain|undefined;try{if(structure&&chainId)sequence=p.viewer.getSequence(structure.id,chainId);}catch{sequence=undefined;}const chains=structure?.alignmentChains||[],annotations=p.scene.flatMap(s=>s.annotations.map(a=>({structure:s,annotation:a}))),selected=new Set(p.selection.structureId===structure?.id?p.selection.residues.map(r=>`${r.chainId}:${r.residueNumber}`):[]);
 async function run(work:(viewer:BiomolViewer)=>Promise<unknown>){setError('');try{await p.onMutate(work);p.onRefresh();}catch(e){setError(e instanceof Error?e.message:String(e));}}
 function measure(type:'distance'|'angle'|'dihedral'|'rmsd'|'radius'){setError('');try{setResult(p.viewer.measureSelection(type));}catch(e){setError(e instanceof Error?e.message:String(e));}}
 function selectRange(){if(!sequence)return;const a=Number(rangeStart),b=Number(rangeEnd);if(!Number.isFinite(a)||!Number.isFinite(b)){setError('Enter the first and last residue number.');return;}p.viewer.clearSelection();for(const residue of sequence.residues.filter(r=>(r.authResidueNumber??r.residueNumber)>=Math.min(a,b)&&(r.authResidueNumber??r.residueNumber)<=Math.max(a,b)))p.viewer.selectSequenceResidue(sequence.structureId,residue,true);}
 const formatted=useMemo(()=>result?`${result.kind==='interface-area'?'Interface area':result.kind[0].toUpperCase()+result.kind.slice(1)}: ${result.value.toFixed(result.unit==='°'?1:2)} ${result.unit}`:'',[result]);
 return localize(<aside className="analysis-panel" aria-label="Structure analysis">
  <header><h2>Structure analysis</h2><button aria-label="Close structure analysis" onClick={p.onClose}>×</button></header>
  <section><h3>Property colors</h3><label>Color by<select value={mapping} disabled={p.busy} onChange={e=>setMapping(e.target.value as ColorMapping)}>{mappings.map(o=><option value={o.id} key={o.id}>{o.label}</option>)}</select></label>{mapping==='custom'&&<label>Scalar values<textarea value={scalar} onChange={e=>setScalar(e.target.value)} rows={4}/><small className="muted">One per line: chain,residue[,atom],value. Missing values appear gray.</small></label>}<button disabled={p.busy||!p.scene.length} onClick={()=>void run(v=>v.setColorMapping(mapping,mapping==='custom'?scalar:undefined))}>Apply color mapping</button></section>
  <section><h3>Automatic annotations</h3><label>Detector<select value={detector} onChange={e=>setDetector(e.target.value as AutoAnnotationMode)}>{detectors.map(o=><option value={o.id} key={o.id}>{o.label}</option>)}</select></label><p className="muted">{detectors.find(o=>o.id===detector)?.help}</p><label>Structure<select value={structure?.id||''} onChange={e=>setStructureId(e.target.value)}>{p.scene.map(s=><option value={s.id} key={s.id}>{s.metadata.fileName}</option>)}</select></label>{detector==='interface-pair'&&<div className="two-fields"><label>Epitope-side chain<select value={chainId} onChange={e=>setChainId(e.target.value)}>{chains.map(c=><option value={c.chainId} key={c.chainId}>{c.authChainId||c.chainId}</option>)}</select></label><label>Paratope-side chain<select value={chainB} onChange={e=>setChainB(e.target.value)}>{chains.map(c=><option value={c.chainId} key={c.chainId}>{c.authChainId||c.chainId}</option>)}</select></label></div>}<button className="primary-button" disabled={p.busy||!structure} onClick={()=>void run(v=>v.autoAnnotate(detector,structure!.id,chainId,chainB))}>Detect and annotate</button>{annotations.map(({structure:s,annotation})=><div className="annotation-row" key={annotation.id}><i style={{background:annotation.color}}/><span><strong>{annotation.name}</strong><small>{s.metadata.fileName} · {annotation.residues.length} residues</small></span><button aria-label={`Remove ${annotation.name}`} onClick={()=>void run(v=>v.removeAnnotation(s.id,annotation.id))}>×</button></div>)}</section>
  <section><h3>Sequence selection matrix</h3><label>Chain<select value={chainId} onChange={e=>setChainId(e.target.value)}>{chains.map(c=><option value={c.chainId} key={c.chainId}>{c.authChainId||c.chainId} · {c.count} residues</option>)}</select></label><label className="zoom-control">Tile zoom<input aria-label="Sequence tile zoom" type="range" min="20" max="56" value={zoom} onChange={e=>setZoom(Number(e.target.value))}/></label><div className="range-select"><input aria-label="First residue" inputMode="numeric" placeholder="First" value={rangeStart} onChange={e=>setRangeStart(e.target.value)}/><input aria-label="Last residue" inputMode="numeric" placeholder="Last" value={rangeEnd} onChange={e=>setRangeEnd(e.target.value)}/><button onClick={selectRange}>Select range</button><button onClick={()=>p.viewer.clearSelection()}>Clear</button></div><div className="sequence-legend"><span className="helix">Helix</span><span className="sheet">Sheet</span><span>Coil</span><span className="confidence">Confidence</span></div><div className="sequence-matrix" aria-label="Linked sequence" style={{'--tile':`${zoom}px`} as React.CSSProperties}>{sequence?.residues.map(residue=><button key={`${residue.residueNumber}${residue.insertionCode||''}`} aria-pressed={selected.has(`${residue.chainId}:${residue.residueNumber}`)} title={`${residue.residueName} ${residue.authResidueNumber??residue.residueNumber}`} className={`sequence-residue ${residue.secondary}`} style={{'--confidence':`${residue.confidence??50}%`,'--annotation':residue.annotations[0]?.color||'transparent'} as React.CSSProperties} onClick={()=>p.viewer.selectSequenceResidue(sequence.structureId,residue,true)}><span>{residue.code}</span><small>{residue.authResidueNumber??residue.residueNumber}</small></button>)}</div></section>
  <section><h3>Measurements</h3><p className="muted">Tap tiles in the order required; tap again to remove. Distance 2, angle 3, dihedral 4, RMSD 6+, radius 2+.</p><div className="measure-grid">{(['distance','angle','dihedral','rmsd','radius'] as const).map(type=><button key={type} disabled={!p.selection.residues.length} onClick={()=>measure(type)}>{type[0].toUpperCase()+type.slice(1)}</button>)}</div><div className="two-fields"><label>Interface chain A<select value={chainId} onChange={e=>setChainId(e.target.value)}>{chains.map(c=><option value={c.chainId} key={c.chainId}>{c.authChainId||c.chainId}</option>)}</select></label><label>Interface chain B<select value={chainB} onChange={e=>setChainB(e.target.value)}>{chains.map(c=><option value={c.chainId} key={c.chainId}>{c.authChainId||c.chainId}</option>)}</select></label></div><button disabled={!structure||chains.length<2} onClick={()=>{try{setResult(p.viewer.measureInterface(structure!.id,chainId,chainB));setError('');}catch(e){setError(e instanceof Error?e.message:String(e));}}}>Calculate interface area</button>{result&&<output className="measurement-result"><strong>{formatted}</strong><span>{result.detail}</span></output>}</section>
  {error&&<p className="fit-warning" role="alert">{error}</p>}
 </aside>,language);
}
