import { localize, useI18n } from '../i18n';
import { useEffect, useMemo, useRef, useState } from 'react';
import type { GalleryOptions, SavedFile, SceneStructure, VideoOptions } from '../viewer/types';
interface Props { busy:boolean;canSave:boolean;scene:SceneStructure[];onClose:()=>void;onExport:(transparent:boolean)=>Promise<SavedFile|undefined>;onShare:()=>Promise<{id:string;url:string}|undefined>;onRecord:(options:VideoOptions)=>Promise<SavedFile|undefined>;onGallery:(options:GalleryOptions)=>Promise<SavedFile|undefined>; }
export function ExportDialog(p:Props){
 const {language}=useI18n(),ref=useRef<HTMLDialogElement>(null);const [transparent,setTransparent]=useState(true),[files,setFiles]=useState<SavedFile[]>([]),[result,setResult]=useState<SavedFile>(),[error,setError]=useState(''),[share,setShare]=useState('');
 const [videoMode,setVideoMode]=useState<VideoOptions['mode']>('rotation'),[axis,setAxis]=useState<VideoOptions['axis']>('y'),[seconds,setSeconds]=useState(6),[video,setVideo]=useState<SavedFile>();
 const [fixed,setFixed]=useState(p.scene[0]?.id||''),[fixedPart,setFixedPart]=useState(''),[candidates,setCandidates]=useState(()=>p.scene.slice(1).map(s=>s.id)),[columns,setColumns]=useState(2),[gallery,setGallery]=useState<SavedFile>();
 const fixedEntry=p.scene.find(s=>s.id===fixed),available=useMemo(()=>p.scene.filter(s=>s.id!==fixed),[p.scene,fixed]);
 async function refresh(){try{const [images,videos]=await Promise.all([fetch('/api/exports'),fetch('/api/videos')]);if(!images.ok||!videos.ok)throw Error();setFiles([...(await images.json()).files,...(await videos.json()).files]);}catch{setError('Exports need the Mac-hosted server.');}}
 useEffect(()=>{ref.current?.showModal();void refresh();},[]);useEffect(()=>setCandidates(previous=>previous.filter(id=>id!==fixed&&p.scene.some(s=>s.id===id))),[fixed,p.scene]);
 async function createShare(){setError('');const saved=await p.onShare();if(saved)setShare(saved.url);else setError('Could not create the shared session.');}
 return localize(<dialog ref={ref} className="open-dialog export-dialog" aria-label="Share and export" onCancel={e=>{e.preventDefault();if(!p.busy)p.onClose();}}>
  <header><h2>Share and export</h2><button disabled={p.busy} onClick={p.onClose} aria-label="Close export">×</button></header>
  <section className="export-section"><h3>Live session link</h3><p className="muted">Save coordinates, transforms, visibility, annotations, style, and camera. Anyone on this Wi-Fi can restore the scene from the link.</p><button className="primary-button" disabled={p.busy||!p.canSave} onClick={()=>void createShare()}>Create session link</button>{share&&<div className="share-result"><input aria-label="Shared session URL" readOnly value={share}/><button onClick={()=>void navigator.clipboard?.writeText(share)}>Copy</button>{typeof navigator.share==='function'&&<button onClick={()=>void navigator.share({title:'Biomol Viewer session',url:share})}>Share…</button>}</div>}</section>
  <section className="export-section"><h3>Scene image</h3><label className="check-row"><input type="checkbox" checked={transparent} onChange={e=>setTransparent(e.target.checked)} disabled={p.busy}/>Transparent background</label><button disabled={p.busy||!p.canSave} onClick={async()=>{setError('');const file=await p.onExport(transparent);if(file){setResult(file);await refresh();}else setError('Export failed. Check the Mac server and output folder.');}}>{p.busy?'Saving…':'Save PNG to Mac'}</button>{result&&<section><p role="status">Saved on Mac: {result.name}</p><a href={result.url} target="_blank" rel="noreferrer"><img className="export-preview" src={result.url} alt="Exported molecular scene"/></a></section>}</section>
  <section className="export-section"><h3>Video</h3><label>Mode<select value={videoMode} onChange={e=>setVideoMode(e.target.value as VideoOptions['mode'])}><option value="rotation">360° scene overview</option><option value="flipbook">Structure flipbook</option></select></label>{videoMode==='rotation'&&<label>Rotation axis<select value={axis} onChange={e=>setAxis(e.target.value as VideoOptions['axis'])}><option value="x">X axis</option><option value="y">Y axis</option><option value="z">Z axis</option></select></label>}<label>Duration · {seconds}s<input type="range" min="2" max="20" value={seconds} onChange={e=>setSeconds(Number(e.target.value))}/></label><button disabled={p.busy||!p.canSave||(videoMode==='flipbook'&&p.scene.length<2)} onClick={async()=>{setError('');const saved=await p.onRecord({mode:videoMode,axis,seconds});if(saved){setVideo(saved);await refresh();}else setError('Video recording failed.');}}>Record and save</button>{video&&<video className="export-preview" controls src={video.url}/>}</section>
  <section className="export-section"><h3>Candidate gallery</h3><p className="muted">Every tile uses the current camera. Keep one receptor structure or chain fixed while candidate structures change.</p><label>Fixed structure<select value={fixed} onChange={e=>{setFixed(e.target.value);setFixedPart('');}}><option value="">None · each structure alone</option>{p.scene.map(s=><option key={s.id} value={s.id}>{s.metadata.fileName}</option>)}</select></label>{fixedEntry&&<label>Fixed component<select value={fixedPart} onChange={e=>setFixedPart(e.target.value)}><option value="">All checked components</option>{fixedEntry.parts.map(part=><option key={part.id} value={part.id}>{part.label}</option>)}</select></label>}<fieldset className="candidate-list"><legend>Moving candidates</legend>{available.map(s=><label className="check-row" key={s.id}><input type="checkbox" checked={candidates.includes(s.id)} onChange={e=>setCandidates(ids=>e.target.checked?[...ids,s.id]:ids.filter(id=>id!==s.id))}/>{s.metadata.fileName}</label>)}</fieldset><label>Columns<select value={columns} onChange={e=>setColumns(Number(e.target.value))}><option value="1">1</option><option value="2">2</option><option value="3">3</option><option value="4">4</option></select></label><button disabled={p.busy||!candidates.length} onClick={async()=>{setError('');const saved=await p.onGallery({fixedStructureId:fixed||undefined,fixedPartId:fixedPart||undefined,candidateIds:candidates,columns,transparent});if(saved){setGallery(saved);await refresh();}else setError('Gallery export failed.');}}>Export synchronized gallery</button>{gallery&&<a href={gallery.url} target="_blank" rel="noreferrer"><img className="export-preview" src={gallery.url} alt="Candidate gallery"/></a>}</section>
  {error&&<p role="alert">{error}</p>}<div className="library-heading"><h3>Saved exports</h3><button disabled={p.busy} onClick={()=>void refresh()}>Refresh exports</button></div><ul className="export-list">{files.map(file=><li key={file.name}><a href={file.url} target="_blank" rel="noreferrer">{file.name}</a>{file.metadataUrl&&<a href={file.metadataUrl} target="_blank" rel="noreferrer">Scene metadata</a>}</li>)}</ul>
 </dialog>,language);
}
